# Generated by Django 6.0.7 on 2026-07-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvgenie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='score',
        ),
        migrations.AddField(
            model_name='resume',
            name='job_description',
            field=models.TextField(blank=True),
        ),
    ]
